### ISSUE TITLE
Travis Failures

### ISSUE THREAD

**Issue by jrmartin** [openworm/org.geppetto.testbackend#59]
The testbackend has a cron job launching the travis build each night. The build sometimes fails, not because of caspers tests not passing, but because one or both of the Dockerfiles fail to build. This has to do with one of the geppetto bundles failing to 'mvn install'

These are the failures I've tracked on the last 5 days, all have failed during the frontend mvn install phase, while trying to retrieve an artifact or a problem with npm installation.

![screenshot 170](https://user-images.githubusercontent.com/4562825/29502751-31f38ac2-85e7-11e7-9c9c-2d9696ab65f8.png)
![screenshot 169](https://user-images.githubusercontent.com/4562825/29502752-31f5515e-85e7-11e7-85e2-9ef48a50e01f.png)
![screenshot 167](https://user-images.githubusercontent.com/4562825/29502753-31f7d398-85e7-11e7-85c1-9d404aaebecb.png)
![screenshot 172](https://user-images.githubusercontent.com/4562825/29502754-31fba77a-85e7-11e7-9a87-bd5d5127a82c.png)
![screenshot 171](https://user-images.githubusercontent.com/4562825/29502755-31fd88ce-85e7-11e7-9061-79bf927cd6ca.png)

**Comment by gidili** [comment]
@jrmartin does it happen on all branches or just on some particular ones?

**Comment by jrmartin** [comment]
@gidili  The testbackend uses the development branches, the cron jobs set up for frontend and persitence also test on development branches. All bundles use the same dockerfiles, but these failures are only happening in the testbackend, one day the cron job fails the other one it passes. Might be something different in the travis.yml for testbackend, but not clear to me yet what it is.

**Comment by tarelli** [comment]
Now travis on testbackend only checks the server side integration tests that are failing because of some updates to NeuroML, for @mattearnshaw to look at when you get a chance.

**Comment by tarelli** [comment]
Hey @mattearnshaw test still failing for me, am I missing something locally?
![Screen Shot 2018-06-16 at 12.48.29.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/536d5766ebef97b1f959c20f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f56b7191a379ed0c2f59415d47be5d4a1f06a3a3dc78e2a436628f5f08edd86f5c71c16f45ace98018ea50e972d84e83b1ea9850d2aa6c7bb3d4d216744b470a83ed5c32aa984eca51f74fe84a52a4123064f43b.png)

**Comment by tarelli** [comment]
Rechecked again, this is still failing, it's preventing the whole bundle to run.  Can you guys please look into it? @mattearnshaw cc @pgleeson 
![screen shot 2018-08-27 at 13 14 59](https://user-images.githubusercontent.com/81127/44659281-8fd84180-a9fb-11e8-85da-c25a3ae289da.png)
